
task :turn_off_alarm do
  puts "Turned off the alarm."
end

task :groom_self do
  puts "Brushed teeth."
  puts "Showered."
  puts "Shaved."
end

task :make_coffee do
  cups = ENV["COFFEE_CUPS"] || 2
  puts "Made #{cups} cups of coffee."
end

task :walk_dog do
  puts "Walked the dog."
end

task :ready_for_the_day => [:turn_off_alarm, :groom_self, :make_coffee, :walk_dog] do
  puts "Ready for the day!"
end

task :default => :ready_for_the_day
